server:
  port: 8082

spring:
  datasource:
    url: jdbc:sqlserver://X.X.X.X:1433;databaseName=152RabbitmqMsg
    username: XX
    password: XXXX
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialize: true
